services:

  arcane:
    image: ghcr.io/ofkm/arcane:latest
    container_name: arcane
    ports:
      - '3030:3000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./arcane-data:/app/data
    environment:
      - APP_ENV=production
      - PUID=1000
      - PGID=1000
      # Generate a strong secret using: openssl rand -base64 32
      - PUBLIC_SESSION_SECRET=your-secure-random-32-character-string-here
      # - PUBLIC_ALLOW_INSECURE_COOKIES=true # Uncomment only for local HTTP testing without SSL/TLS.
    restart: unless-stopped
